# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import math_engine_pb2 as math__engine__pb2

GRPC_GENERATED_VERSION = '1.83.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in math_engine_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class MathEngineServiceStub:
    """------------------------------------------------------------------
    Service
    ------------------------------------------------------------------

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CalculatePortfolio = channel.unary_unary(
                '/finsimai.math_engine.MathEngineService/CalculatePortfolio',
                request_serializer=math__engine__pb2.CalculatePortfolioRequest.SerializeToString,
                response_deserializer=math__engine__pb2.CalculatePortfolioResponse.FromString,
                _registered_method=True)
        self.GenerateNextPrices = channel.unary_unary(
                '/finsimai.math_engine.MathEngineService/GenerateNextPrices',
                request_serializer=math__engine__pb2.GenerateNextPricesRequest.SerializeToString,
                response_deserializer=math__engine__pb2.GenerateNextPricesResponse.FromString,
                _registered_method=True)
        self.CalculateRiskMetrics = channel.unary_unary(
                '/finsimai.math_engine.MathEngineService/CalculateRiskMetrics',
                request_serializer=math__engine__pb2.CalculateRiskMetricsRequest.SerializeToString,
                response_deserializer=math__engine__pb2.CalculateRiskMetricsResponse.FromString,
                _registered_method=True)
        self.CheckPenaltyStatus = channel.unary_unary(
                '/finsimai.math_engine.MathEngineService/CheckPenaltyStatus',
                request_serializer=math__engine__pb2.CheckPenaltyStatusRequest.SerializeToString,
                response_deserializer=math__engine__pb2.CheckPenaltyStatusResponse.FromString,
                _registered_method=True)


class MathEngineServiceServicer:
    """------------------------------------------------------------------
    Service
    ------------------------------------------------------------------

    """

    def CalculatePortfolio(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GenerateNextPrices(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CalculateRiskMetrics(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CheckPenaltyStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MathEngineServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CalculatePortfolio': grpc.unary_unary_rpc_method_handler(
                    servicer.CalculatePortfolio,
                    request_deserializer=math__engine__pb2.CalculatePortfolioRequest.FromString,
                    response_serializer=math__engine__pb2.CalculatePortfolioResponse.SerializeToString,
            ),
            'GenerateNextPrices': grpc.unary_unary_rpc_method_handler(
                    servicer.GenerateNextPrices,
                    request_deserializer=math__engine__pb2.GenerateNextPricesRequest.FromString,
                    response_serializer=math__engine__pb2.GenerateNextPricesResponse.SerializeToString,
            ),
            'CalculateRiskMetrics': grpc.unary_unary_rpc_method_handler(
                    servicer.CalculateRiskMetrics,
                    request_deserializer=math__engine__pb2.CalculateRiskMetricsRequest.FromString,
                    response_serializer=math__engine__pb2.CalculateRiskMetricsResponse.SerializeToString,
            ),
            'CheckPenaltyStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.CheckPenaltyStatus,
                    request_deserializer=math__engine__pb2.CheckPenaltyStatusRequest.FromString,
                    response_serializer=math__engine__pb2.CheckPenaltyStatusResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'finsimai.math_engine.MathEngineService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('finsimai.math_engine.MathEngineService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class MathEngineService:
    """------------------------------------------------------------------
    Service
    ------------------------------------------------------------------

    """

    @staticmethod
    def CalculatePortfolio(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/finsimai.math_engine.MathEngineService/CalculatePortfolio',
            math__engine__pb2.CalculatePortfolioRequest.SerializeToString,
            math__engine__pb2.CalculatePortfolioResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GenerateNextPrices(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/finsimai.math_engine.MathEngineService/GenerateNextPrices',
            math__engine__pb2.GenerateNextPricesRequest.SerializeToString,
            math__engine__pb2.GenerateNextPricesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CalculateRiskMetrics(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/finsimai.math_engine.MathEngineService/CalculateRiskMetrics',
            math__engine__pb2.CalculateRiskMetricsRequest.SerializeToString,
            math__engine__pb2.CalculateRiskMetricsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CheckPenaltyStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/finsimai.math_engine.MathEngineService/CheckPenaltyStatus',
            math__engine__pb2.CheckPenaltyStatusRequest.SerializeToString,
            math__engine__pb2.CheckPenaltyStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
